spring.application.name=ShoppingApp

# ? Persist H2 data on disk (instead of memory)
spring.datasource.url=jdbc:h2:file:./data/peepii
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ? Keep tables/data between restarts
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# (optional, but useful)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.defer-datasource-initialization=true


app.jwt.expiration-ms=86400000

app.jwt.secret=9Pqv2m9xWk8ZcYJmN7tH5sK2rQ6bV1eL8dF3aZ0xC4uJ7nS5pR2mQ9vXk8ZcYJm
