package PPs.ShoppingApp.Dto;

import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class ProductDTO {

    // Usually generated by DB,  it nullable for create requests
    private Integer id;

    @NotBlank(message = "name is required")
    @Size(min = 2, max = 120, message = "name must be between 2 and 120 characters")
    private String name;

    @Size(max = 1000, message = "description must be at most 1000 characters")
    private String description;

    @NotBlank(message = "brand is required")
    @Size(min = 2, max = 80, message = "brand must be between 2 and 80 characters")
    private String brand;

    @NotNull(message = "price is required")
    @DecimalMin(value = "0.0", inclusive = false, message = "price must be greater than 0")
    private BigDecimal price;

    @NotBlank(message = "category is required")
    @Size(min = 2, max = 50, message = "category must be between 2 and 50 characters")
    private String category;

    @NotNull(message = "releaseDate is required")
    @PastOrPresent(message = "releaseDate cannot be in the future")
    private Date releaseDate;

    // boolean cannot be null; no @NotNull needed
    private boolean productAvailable;

    @NotNull(message = "stockQuantity is required")
    @Min(value = 0, message = "stockQuantity must be 0 or more")
    private Integer stockQuantity;

    @Size(max = 255, message = "imageName must be at most 255 characters")
    private String imageName;

    @Pattern(
            regexp = "^(image\\/png|image\\/jpeg|image\\/jpg|image\\/webp)$",
            message = "imageType must be one of: image/png, image/jpeg, image/jpg, image/webp"
    )
    private String imageType;
}
